trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
#   - name: AppName
#     value: 'varapp' # Leave it empty for now, we'll fetch it from Key Vault
#   - name: PortNumber
#     value: '0002' # Leave it empty for now, we'll fetch it from Key Vault
  - name: PropertiesFilePath
    value: '$(System.DefaultWorkingDirectory)/src/main/resources/application.properties'

jobs:
- job: BuildAndReplaceProperties
  steps:
  - checkout: self

  # Fetch values from Azure Key Vault
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Az'
      KeyVaultName: 'variablecheck'
      SecretsFilter: '*'
      RunAsPreJob: false

  
  - script: |
      # Debug: Print environment variables
      echo "APPNAMEE: $AZURE_KEYVAULT_SECRET_APPNAMEE"
      echo "PORTNUMBER: $AZURE_KEYVAULT_SECRET_PORTNUMBERR"
    displayName: 'Display Key Vault Values'