trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

# variables:
#   - group: keyvault  # Replace with your variable group name

# variables:
#   - name: AppName
#     value: 'varapp' # Leave it empty for now, we'll fetch it from Key Vault
#   - name: PortNumber
#     value: '0002' # Leave it empty for now, we'll fetch it from Key Vault
#   - name: PropertiesFilePath
#     value: '$(System.DefaultWorkingDirectory)/src/main/resources/application.properties'

jobs:
- job: BuildAndReplaceProperties
  steps:
  - checkout: self

  # Fetch values from Azure Key Vault
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Az'
      KeyVaultName: 'variablecheck'
      SecretsFilter: '*'
      RunAsPreJob: false

  
  - script: |
      # Display the values directly from Azure Key Vault secrets
      echo "APPNAME: $(AZURE_KEYVAULT_SECRET_APPNAME)"
      echo "PortNumber: $(AZURE_KEYVAULT_SECRET_PORTNUMBER)"
    displayName: 'Display Key Vault Values'