trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: KeyVaultVariables

jobs:
- job: DisplayKeyVaultValues
  steps:
  - checkout: self

  # Fetch values from Azure Key Vault and set environment variables
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Az'
      KeyVaultName: 'variablecheck'
      SecretsFilter: '*'
      RunAsPreJob: false

  - script: |
      # Debug: Print environment variables
      echo "APPNAMEE: $AZURE_KEYVAULT_SECRET_APPNAMEE"
      echo "PORTNUMBER: $AZURE_KEYVAULT_SECRET_PORTNUMBERR"
    displayName: 'Display Key Vault Values'

  # Add more steps as needed for further debugging or actions
