trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: NewAppName
    value: 'azureapp'
  - name: NewPort
    value: '9090'
  - name: PropertiesFilePath
    value: '$(System.DefaultWorkingDirectory)/target/application.properties'

jobs:
- job: ReplaceProperties
  steps:
  - checkout: self

  - script: |
      # Debugging: List contents of the working directory
      ls -R $(System.DefaultWorkingDirectory)

      # Replace values in application.properties
      sed -i 's/^spring.application.name=.*/spring.application.name=$(NewAppName)/' $(PropertiesFilePath)
      sed -i 's/^server.port=.*/server.port=$(NewPort)/' $(PropertiesFilePath)
    displayName: 'Replace values in application.properties'

  - script: |
      # Debugging: List contents of the target directory
      ls -R $(System.DefaultWorkingDirectory)/target
    displayName: 'List contents of the target directory'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
      ArtifactName: 'my-artifact'
      publishLocation: 'Container'
