trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: KeyVaultVariables

jobs:
- job: BuildAndReplaceProperties
  steps:
  - checkout: self

  # Fetch values from Azure Key Vault and set environment variables
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Az'
      KeyVaultName: 'variablecheck'
      SecretsFilter: '*'
      RunAsPreJob: false

  - script: |
      # Debug: Print current directory and contents of the directory
      echo "Current Directory: $(pwd)"
      echo "Contents of $(PropertiesFilePath):"
      cat $(PropertiesFilePath)

      # Replace values in application.properties using environment variables
      sed -i "s/^spring.application.name=.*$/spring.application.name=$APPNAME/" $(PropertiesFilePath)
      sed -i "s/^server.port=.*$/server.port=$PORTNUMBER/" $(PropertiesFilePath)

      # Debug: Print the modified contents of the file
      echo "Modified Contents of $(PropertiesFilePath):"
      cat $(PropertiesFilePath)
    displayName: 'Replace values in application.properties'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-DskipTests'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
      ArtifactName: 'my-artifact'
      publishLocation: 'Container'
    displayName: 'Publish artifact'
