trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DisplayKeyVaultValues
  steps:
  - checkout: self

  # Fetch values from Azure Key Vault
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Az'
      KeyVaultName: 'variablecheck'
      SecretsFilter: '*'
      RunAsPreJob: false

  - powershell: |
      # Display values directly from Azure Key Vault
      Write-Host "Original APPNAME: $env:AZURE_KEYVAULT_SECRET_APPNAME"
      Write-Host "Original PortNumber: $env:AZURE_KEYVAULT_SECRET_PORTNUMBER"
    displayName: 'Display Key Vault Values'

  # Add more steps as needed for further actions
