trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DisplayKeyVaultValues
  steps:
  - checkout: self

  # Fetch values from Azure Key Vault
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Az'
      KeyVaultName: 'variablecheck'
      SecretsFilter: '*'
      RunAsPreJob: false

  - powershell: |
      # Display values directly from Azure Key Vault
        echo $(PORTNUMBERR) > check.txt
    displayName: 'Display Key Vault Values'

  # Add more steps as needed for further actions 

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(System.DefaultWorkingDirectory)'
      contents: 'check.txt'  # Copy all files
      targetFolder: '$(Build.ArtifactStagingDirectory)/staging'

  # Publish files as artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/staging'
      ArtifactName: 'my-artifact'
      publishLocation: 'Container'